[package]
name = "regenkfs"
version = "0.1.0"
authors = ["Ben Siraphob <bensiraphob@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
structopt = "0.3.20"

[features]
c-undef = []

default = []
